Redux class action
ethul/purescript-react-redux pull request #6
Opened 2017-01-19 23:14 UTC by BartAdv

* Parameterize `ReduxReactClass` by an action type, change type parameters order to make it uniform with React-bindings Spec: props goes first, then state, and actions come last, as they're addition here

* Alter type signature of `Middleware`, to reflect the fact that it can be composed and thus next middleware in chain can receive different action type.

TODO: `semigroupoid` instance for `Middleware` - that seems to require `Middleware` to be `newtype` rather than type synonym, which has some ugly consequences...

Also, it's late already and I'm not 100% sure I've made everything right, but openened this PR so that you can play around/check. I've also modified Example app to include some (useless) different Action types showing how the composition works: https://github.com/BartAdv/purescript-react-redux-example/commit/f3029e0f92f5bebff668acac0b45b57b062eea98

2017-01-20 04:49 UTC, ethul commented
Thanks for putting together this PR! Looking good.

I will take a closer look and dig in this weekend.

Thanks again for working on this!

2017-01-22 14:07 UTC, ethul commented
I've been digging into the changes and mainly I'd like to further discuss the changes to the `Middleware` type.

Is there a driving use-case that you have in mind for having the middleware call `next` with a different type of action from the type of the store's action?

I was thinking that perhaps the use-case could be if there was an external middleware published and a user wanted to incorporate it into their app. However, the user would still have to map between their action type and the external. Consider the following example.

```purescript
data ExternalAction = External1 | External2

externalMiddleware :: forall eff action state. Redux.Middleware eff action state Unit ExternalAction ExternalAction
externalMiddleware _ next =
  case _ of
       External1 -> next External2
       External2 -> next External1
```

Then in your app you could have:

```purescript
externalMiddlewareTo :: Redux.Middleware (Effect eff) Action State Unit Action ExternalAction
externalMiddlewareTo _ next = -- ...

externalMiddlewareFrom :: Redux.Middleware (Effect eff) Action State Unit ExternalAction Action
externalMiddlewareFrom _ next = -- ...
```

And compose them:

```purescript
externalMiddlewareFrom `composeMiddleware` externalMiddleware `composeMiddleware` externalMiddlewareTo
```

I am not sure if the above is clear, but I suppose adding the extra `action` type parameter makes something like this possible. Whereas before, I don't believe something like this is would have been possible.

Do you think this would be the main use-case for adding the extra `action` type? Curious on your take.

2017-01-22 14:20 UTC, ethul requested changes

2017-01-22 14:20 UTC, ethul commented on src/React/Redux.js
> +          var result = middlewareB(middlewareAPI)(middlewareA(middlewareAPI)(next))(action)();
I think something is not lining up here. I was trying to compose more than two middlewares, but it results in:
```Cannot read property 'constructor' of undefined```

2017-01-22 14:20 UTC, ethul commented on src/React/Redux.purs
> +import Prelude (Unit, const, id, pure, unit, (<<<), (>>=))
Can we put `Prelude` as the first import? I think it's pretty common amongst PureScript libraries to have this up top. We could also have it as an open import (e.g., `import Prelude`)

2017-01-22 14:20 UTC, ethul commented on src/React/Redux.purs
> -import React as React
I think I'd like the `React` import towards the bottom here like it was. Usually, I try to keep all the non-core imports below the core ones. I am considering core imports to be `Prelude`, `Control`, `Data`, etc.

2017-01-22 14:20 UTC, ethul commented on src/React/Redux.purs
> -
Sorry to nit-pick, but can we keep the spacing between the imports?

2017-01-22 14:20 UTC, ethul commented on src/React/Redux.purs
> -
Please keep spacing

2017-01-22 14:20 UTC, ethul commented on src/React/Redux.purs
>  foreign import dispatch_ :: forall eff action props state. Fn2 (React.ReactThis props state) action (Eff (ReduxEffect eff) action)
Should the order of the type parameters be `eff props state action`? This comment applies generally. There are something other functions where `action` is still before `state`. Not sure if we decided to reorder these too or not.

2017-01-22 15:23 UTC, BartAdv commented
I'll address other issues later on, but as for the driving use case for Middleware type I'll blatantly say - I don't have one. It was something that struck me when browsing redux docs - they use this to allow action to be function for example (redux-thunk) etc. So it's just to make it in line with what redux offers. But I'm pretty sure we don't need to rely that much on Middleware here, in PS, as we have Aff etc...

2017-01-24 02:05 UTC, ethul commented
Thank you very much for making the updates. Looking good. Understood about the middleware. I am still thinking about this a bit.

2017-01-24 02:05 UTC, ethul approved these changes

2017-10-02 21:36 UTC, closed without merging